version: '2'

volumes:
  orderer.orderermanagement.com:
  peer0.audi.orderermanagement.com:
  peer1.audi.orderermanagement.com:
  peer0.bridgestone.orderermanagement.com:
  peer1.bridgestone.orderermanagement.com:
  peer0.mrf.orderermanagement.com:
  peer1.mrf.orderermanagement.com:

networks:
  auto:

services:

  orderer.orderermanagement.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.orderermanagement.com
    container_name: orderer.orderermanagement.com
    networks:
      - auto

  peer0.audi.orderermanagement.com:
    container_name: peer0.audi.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.audi.orderermanagement.com
    networks:
      - auto

  peer1.audi.orderermanagement.com:
    container_name: peer1.audi.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.audi.orderermanagement.com
    networks:
      - auto

  peer0.bridgestone.orderermanagement.com:
    container_name: peer0.bridgestone.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bridgestone.orderermanagement.com
    networks:
      - auto

  peer1.bridgestone.orderermanagement.com:
    container_name: peer1.bridgestone.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bridgestone.orderermanagement.com
    networks:
      - auto

  peer0.mrf.orderermanagement.com:
    container_name: peer0.mrf.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.mrf.orderermanagement.com
    networks:
      - auto

  peer1.mrf.orderermanagement.com:
    container_name: peer1.mrf.orderermanagement.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.mrf.orderermanagement.com
    networks:
      - auto

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.audi.orderermanagement.com:7051
      - CORE_PEER_LOCALMSPID=AudiMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/audi.orderermanagement.com/peers/peer0.audi.orderermanagement.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/audi.orderermanagement.com/peers/peer0.audi.orderermanagement.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/audi.orderermanagement.com/peers/peer0.audi.orderermanagement.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/audi.orderermanagement.com/users/Admin@audi.orderermanagement.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.orderermanagement.com
      - peer0.audi.orderermanagement.com
      - peer1.audi.orderermanagement.com
      - peer0.bridgestone.orderermanagement.com
      - peer1.bridgestone.orderermanagement.com
      - peer0.mrf.orderermanagement.com
      - peer1.mrf.orderermanagement.com
    networks:
      - auto
