Organizations:
    - &Org4
        Name: AuditorMSP
        ID: AuditorMSP
        MSPDir: crypto-config/peerOrganizations/auditor.orderermanagement.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AuditorMSP.admin', 'AuditorMSP.peer', 'AuditorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AuditorMSP.admin', 'AuditorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AuditorMSP.admin')"
        AnchorPeers:
            - Host: peer0.auditor.orderermanagement.com
              Port: 13051
